//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPLStatsWebAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int EntryId { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public int GamesWon { get; set; }
        public int GamesLost { get; set; }
        public int WeekNumber { get; set; }
    }
}
