//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPLStatsWebAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Week
    {
        public int Id { get; set; }
        public int WeekNumber { get; set; }
        public Nullable<bool> WeekWon { get; set; }
        public Nullable<System.DateTime> DatePlayed { get; set; }
        public Nullable<int> TeamPlayed { get; set; }
        public Nullable<bool> Home { get; set; }
        public Nullable<bool> Forfeit { get; set; }
    }
}
